get account id from afp api to use it in costLink for cloudhealth
ImmobilienScout24/afp-web pull request #10
Opened 2017-10-20 14:23 UTC by mlefringhausen

https://..../afp-api/latest/account?withid 
returns 
'"testaccount": {"id": "123456789012", "roles": ["testrole"]}'

2017-10-20 15:01 UTC, SebastianStiehl requested changes

2017-10-20 15:01 UTC, SebastianStiehl commented on js/service/userMessageService.js
> +            'AccountID': details['id']
Object key access is better written with the dot notation. `details.id`

2017-10-20 15:01 UTC, SebastianStiehl commented on js/service/userMessageService.js
> +          angular.forEach(details['roles'], function (role) {
Same here. Object key access is better written with the dot notation. `details.roles`

2017-10-20 15:01 UTC, SebastianStiehl commented on js/service/userMessageService.js
> +        var account = "";
The account setup can be done in the beginning and filled in later.
```
var account = {
  'AccountName': accountName,
  'Roles': []
};

...

account.AccountID = details.id;
```

2017-10-23 11:03 UTC, closed without merging

2017-10-23 11:04 UTC, mlefringhausen commented
I did the requested changes and will create a new pull request